### ISSUE TITLE
Waiting for roots to load... error message

### ISSUE THREAD

**Issue by richb-hanover** [facebook/react-devtools#354]
I'm using React Developer Tools 0.14.9 on Chrome Version 50.0.2661.49 beta (64-bit) (OSX 10.10.5). I have cloned react-starter-kit (https://github.com/kriasoft/react-starter-kit) and modified it to make my app. 

I tested the original react-starter-kit, and it works fine - it displays the React components as desired. 

But when I fire up my app and inspect it, the React tab shows "Waiting for roots to load ... to reload the inspector [ click here ]"

What causes this message? Where do the "roots" come from? (I'm sure I have screwed something up, but ... what?) Thanks.

**Comment by 2color** [comment]
I'm getting the same error.

In the console I see:
`backend.js:8441 Uncaught TypeError: Cannot read property 'props' of undefined`

**Comment by Kasu** [comment]
I'm writing a custom react renderer (https://github.com/Kasu/symphony/tree/custom-renderer/lib/surface/react-surface) and I'm experiencing the same problem. It could be related to this issue.

 If not, I'd still be greatful in some advice on where to in react-devtools to understand where the roots come from. I tried to track down the "root" event from the bridge but I couldn't find where in react it comes from.

**Comment by spicyj** [comment]
It probably comes from the "backend" folder. No one actively works on the devtools and has a good understanding of all the pieces so you'll have to dig around if you want to change stuff.

**Comment by Kasu** [comment]
@spicyj Found it! Thanks for the pointer!

It's `hook.emit("root", ...)` in https://github.com/facebook/react-devtools/blob/master/backend/attachRenderer.js

**Comment by BobWhitelock** [comment]
I'm getting a similar error as described in https://github.com/facebook/react-devtools/issues/105#issuecomment-206450315.

**Comment by BobWhitelock** [comment]
I've investigated this some more, and I've been able to reproduce this issue consistently with the following gist: https://gist.github.com/BobWhitelock/8a3fd237a325668e659465a20555c84b. This should able to just be downloaded and the page viewed as-is, and the issue can be seen in the devtools and the error message within the console.

The error, at least in my case, seems to be due to the dynamic text creation using `{}` within the `option` element, the error only appears when this is present - I've no idea why this is causing this however.

**Comment by spicyj** [comment]
@BobWhitelock Sounds like #248.

**Comment by BobWhitelock** [comment]
Thanks @spicyj, that does look the same. Looks like there's a possible fix proposed in https://github.com/facebook/react-devtools/pull/345 also, but I've managed to work around this for the moment by creating the option text elsewhere and ensuring the option only has a single child.

**Comment by gertcuykens** [comment]
I still have this error when pre render my page? Note that I am new to react and don't understand much about it yet.

```
<!DOCTYPE html>                                                                                                         
<html>  
  <head>                                                                                                                
    <title>Test</title>                                                                                                                                                        
    <script src="react.min.js"></script>
    <script src="react-dom.min.js"></script>                                                                              
  </head>                                                                                                               
  <body>                                                                          
  <div data-reactroot="" data-reactid="1" data-react-checksum="318384820"><!-- react-text: 2 -->Hello <!-- /react-text -
-><!-- react-text: 3 -->John<!-- /react-text --></div>                                                                  
  </body>                                                                                                               
<html>
```

**Comment by mapimienta** [comment]
you must to add this: 
<script src="https://npmcdn.com/babel-core@5.8.38/browser.min.js"></script>

**Comment by mapimienta** [comment]
you must to add this js:
https://npmcdn.com/babel-core@5.8.38/browser.min.js

**Comment by gaearon** [comment]
This was likely a DevTools bug that got fixed in https://github.com/facebook/react-devtools/issues/345. Closing.

**Comment by Slapbox** [comment]
Still seeing this issue with React Devtools in Electron. Hadn't seen it until just today.

**Comment by gaearon** [comment]
@Slapbox What are you using it with? If React Native, it might be due to a bug in RN that is fixed in master. You can try applying https://github.com/facebook/react-native/pull/12305 and https://github.com/facebook/react-native/pull/12316 to RN locally. If you still experience it, please file an issue describing exactly how to reproduce this.

**Comment by Slapbox** [comment]
@gaearon Thanks for your response. I'm not using React Native. I made a report at #547

**Comment by sunkarashruthi** [comment]
Hey guys, 

i am a beginner to react. My broswer is not rendering the hello world that i rendered in my js file.
I am attaching two examples screenshot
![react-issue](https://cloud.githubusercontent.com/assets/13577815/25253991/3527c02e-25d8-11e7-8de9-b33a51231b2f.PNG)
![r2](https://cloud.githubusercontent.com/assets/13577815/25253996/39f6ab42-25d8-11e7-9215-c82399e1a940.PNG)

first image: i was running webpack-dev-server at localhost:8080, instead of displaying hello world it displays the way in the image

second image: This was displaying hello world when running the index.html file but the dev tools has error like waiting to load....

any suggestions would really help me
Thanks

**Comment by sunkarashruthi** [comment]
Also React dev tools is not showing in the console of my first image

**Comment by Slapbox** [comment]
@sunkarashruthi I have run into this issue a few times and every single time it has been my own fault.

Are there any warnings or errors? That can cause this.

Is there anything that could possibly be happening in a way you don't expect that is not technically an error? In particular, check your `ComponentWillMount()`'s first and foremost.

**Comment by sunkarashruthi** [comment]
@Slapbox  Thanks for responding

Yes, i see one of them

XMLHttpRequest cannot load file:///C:/Users/SHRUTHI/Desktop/practise/kode/component.min.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

component.js
import React from "react";
import ReactDOM from "react-dom";


class Layout extends React.Component{
	render(){
		return(
            <h1> Hello World!</h1>
			);
	}
}
ReactDOM.render(<Layout/>, document.getElementById('app'));

index.html
<!DOCTYPE html>
<html>

<head>
<meta charset ="utf-8">
<title> React basics </title>

 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

 </head>

 <body>
 <div class ="container">
 <h1>React basic example</h1>
 </div>

 <div id="app">
 <p> Why its waiting for roots to load</p>
   <script src='https://fb.me/react-15.0.1.js'></script>
    <script src='https://fb.me/react-dom-15.0.1.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js'></script>

        <script type="text/babel" src="component.min.js"> </script>
 </body>
 </html>
webpack.config.js

var debug = process.env.NODE_ENV !== "production";
var webpack = require('webpack');

module.exports = {
  context: __dirname+ "/src",
  devtool: debug ? "inline-sourcemap" : null,
  entry: "./component.js",
  module:{
    loaders:[
{
  test: /\.js?$/,
  exclude:/(node_modules|bower_components)/,
  loader: 'babel-loader',
  query:{
    presets:['react', 'es2015', 'stage-0'],
    plugins:['react-html-attrs', 'transform-class-properties', 'transform-decorators-legacy']
  }
}
    ]
  },
  output: {
    path: __dirname + "/src/",
    filename: "component.min.js"
  },
  plugins: debug ? [] : [
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({ mangle: false, sourcemap: false }),
  ],
};

package.json

{
  "name": "kode",
  "version": "1.0.0",
  "description": "test",
  "main": "component.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack -p",
    "dev": "webpack -d --watch",
    "dev": "webpack-dev-server"
  },
  "author": "ss",
  "license": "ISC",
  "dependencies": {
    "babel-core": "^6.24.1",
    "babel-loader": "^6.4.1",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "latest-version": "^3.1.0",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "webpack": "^2.4.1",
    "webpack-dev-server": "^2.4.2"
  },
  "devDependencies": {
    "redux-devtools": "^3.1.1"
  }
}

Also wheni run webpack i got the minified version component.min.js (is so huge so i m not sharing here)

Pl check the hello world example & let me know if i did any mistake,  i put lot of efforts but could not figure out cross domain issue even after reading forums
