### ISSUE TITLE
Uncaught TypeError: node.getBoundingClientRect is not a function in backend.js ln 9046

### ISSUE THREAD

**Issue by nwinger** [facebook/react-devtools#362]
I just got this error in my chrome console today:

> Uncaught TypeError: node.getBoundingClientRect is not a function.

It appears every time I hover an element in the dev tools extension. See attached screenshot.
I am on version 0.14.9 and Chrome is Version 50.0.2661.66 beta-m (64-bit)

![image](https://cloud.githubusercontent.com/assets/859037/14519514/cb35e650-021f-11e6-928d-c33ef8a82788.png)

**Comment by jclgoodwin** [comment]
I'm having the same problem (React Developer Tools 0.14.9, React 15.0.1, Chrome 49). I think it's related to a change in React 15.0.0. It seems to occur when `node` is a `comment`.

**Comment by Arnavion** [comment]
Right-clicking on the text node and selecting "Scroll to node" from the context menu throws [`backend.js:396: Uncaught TypeError: node.scrollIntoView is not a function`](https://github.com/facebook/react-devtools/blob/2beafbf/agent/Agent.js#L205) for the same reason (`node` is a comment node).

**Comment by jaredly** [comment]
Is this then fixed now that #361 is merged?

**Comment by boazblake** [comment]
still a problem

**Comment by ocularrhythm** [comment]
For me, the error seems to only throw when I hover over a `Text Node`

**Comment by qikkeronline** [comment]
Same here, only when hovering a text node

**Comment by gluons** [comment]
Same here on Firefox 50

**Comment by QuickITDotnet** [comment]
Hi All,
Any Update on this issue? I am still facing same issue as mentioned.

node.getBoundingClientRect is not a function

**Comment by Luksys5** [comment]
Same Here

**Comment by gaearon** [comment]
This was fixed by #361 but we mistakingly shipped an old version to Firefox addons website.
We’ll release an update in a day or two with some new fixes, including this fix.

**Comment by Arnavion** [comment]
@gaearon https://github.com/facebook/react-devtools/issues/362#issuecomment-212701157 is not fixed by that PR, as I pointed out in https://github.com/facebook/react-devtools/pull/361#issuecomment-212703004

**Comment by gaearon** [comment]
@Arnavion Yes but it will be fixed by #413

**Comment by Arnavion** [comment]
Cool, thanks.

**Comment by gaearon** [comment]
Firefox version was also updated now with a fix (and a bunch of other fixes that mistakingly weren’t deployed for a few months 😄 ).
