### ISSUE TITLE
High CPU when tab is in background

### ISSUE THREAD

**Issue by agos** [facebook/react-devtools#739]
**Summary:** when developer tools are left open on a background fullscreen Chrome window, 100% CPU usage happens. React-devtools looks like the cause.

**Browser Versions:** Chrome 59 (fairly sure happened with 58 as well)
**Operating System:** macOS 10.12.5

**Steps to reproduce:**

1. Put a Chrome window fullscreen (either normal or split screen)
2. Navigate to random URL. Not necessary for it to be a React App.
3. Open inspector
4. Switch to another desktop / app

**Expected behaviour:**

The extension uses no CPU, since

1) the inspector is not open on a React app
2) the inspector is not focused
3) the relevant Chrome window is not visible

**Actual behaviour:**

CPU usage goes to 99.9% (one full core). Chrome's task manager says it's the developer tools.

**Other useful info:**

- Switching back to the fullscreen tab with the developer tools fixes the issue
- Disabling the React devtools extension fixes the issue
- Above was tested with only React devtools extension enabled
- No errors are present in react-devtools console or in the inspected views - background page section

**Comment by gaearon** [comment]
Thanks for the report. Would you be interested in looking into the cause?

**Comment by agos** [comment]
@gaearon sure, absolutely! What can I do to provide additional data?

**Comment by noodny** [comment]
@gaearon got the same issue in Chrome 59 - the only difference is that my chrome isn't fullscreen and I'm not even switching programs, just moving to a different chrome tab

**Comment by gaearon** [comment]
Please feel free to debug what happens. My guess is something related to our use of `requestIdleCallback` [here](https://github.com/facebook/react-devtools/blob/d971871fb7f5b3b513b1902fc05543b907edec3f/agent/Bridge.js#L245). Maybe it never gets called and events accumulate, or something like this.

**Comment by dennistang** [comment]
Tried taking a stab at debugging it, seems to be something with `loadCheckInterval` in [main.js:56](https://github.com/facebook/react-devtools/blob/d971871fb7f5b3b513b1902fc05543b907edec3f/shells/chrome/src/main.js#L56) (shells/chrome/src/main.js) and how it calls `createPanelIfReactLoaded` every second.
<img width="406" alt="bildschirmfoto 2017-06-07 um 18 12 47" src="https://user-images.githubusercontent.com/247852/26908245-5036d822-4bae-11e7-8775-3c5b1d17073f.png">

My best guess would be that `createPanelIfReactLoaded` tries to have the inspected window run that [eval](https://github.com/facebook/react-devtools/blob/d971871fb7f5b3b513b1902fc05543b907edec3f/shells/chrome/src/main.js#L21-L23) since in the profile I've attached it shows that `_onMessage` is carrying that same `eval`.
<img width="736" alt="bildschirmfoto 2017-06-07 um 18 13 44" src="https://user-images.githubusercontent.com/247852/26908252-59d69fd4-4bae-11e7-8297-ef93aa119555.png">
<img width="1226" alt="bildschirmfoto 2017-06-07 um 18 14 08" src="https://user-images.githubusercontent.com/247852/26908258-62044c9c-4bae-11e7-8a21-40e1ee9ca55f.png">

I don't know enough about extension development to know if that's a no-no when you try to have a tab execute an eval in the background. I thought Chrome would limit it like it does with normal background tabs but perhaps not with devtools?

Note: it seems to only happen when the inspector is docked to the page, if it's broken out into its own window it doesn't seem to pin the CPU.

Hope this helps!

[React-DevTools-CPU-Profile-20170607T180907.json.zip](https://github.com/facebook/react-devtools/files/1059703/React-DevTools-CPU-Profile-20170607T180907.json.zip)

**Comment by ochrons** [comment]
I'm seeing same behavior on Chrome 59 on Win10. Each devtools tab is using 100% CPU when in the background. Disabling React Tools and restarting Chrome makes this problem go away.

Did not happen on Chrome 58 AFAICT.

**Comment by yuezk** [comment]
On every page which not use React, open the devtools, and switch to another tab, cpu 100% usage.

**Comment by dennistang** [comment]
It's possible that this is an issue specific to Chrome 59; I'm not able to reproduce this in Chrome Beta (60.0.3112.24) or Chromium (61.0.3130.0).

**Comment by phodal** [comment]
It seems this issues was caused by setInterval, and in Chrome 59 add a new feature about setInterval.

In here, was a simplify code from react dev tools with setInterval:  https://github.com/phodal/chrome-59-show-setinterval-issue-code

I don't had to many experience on debug Chrome, so just leave a issue on Google Chromium bug page, which is https://bugs.chromium.org/p/chromium/issues/detail?id=733469

**Comment by 0xcaff** [comment]
Basically a regression of `setInterval` leaked into the stable release of chrome. Updating to >=59.0.3071.109 will fix this problem.

**Comment by dennistang** [comment]
Yep! I'm no longer experiencing high CPU usage!

**Comment by agos** [comment]
since this appears to be a Chrome issue and resolved in the latest version, I'll close the issue.

**Comment by selrond** [comment]
Still happening to me, `Version 66.0.3359.117 (Official Build) (64-bit)`...

**Comment by StipJey** [comment]
Faced with this problem. The computer heats up like a stove
_Chrome 72.0.3626.121 (64-bit)
React Developer Tools 3.6.0
MacOS 10.14.3_
