### ISSUE TITLE
"Type error for exceptionInfo value (Property "isException" is required) for devtools.inspectedWindow.eval." when opening Firefox devtools

### ISSUE THREAD

**Issue by squelart** [facebook/react-devtools#873]
STR:
- Build Firefox and run from a terminal
- Install the React Devtools add-on
- Open the devtools (not necessarily the React tab itself)

Looking at the terminal, I see the following error once per second:

> Extension error: Error: Type error for exceptionInfo value (Property "isException" is required) for devtools.inspectedWindow.eval.  0
> [[Exception stack
> Async*createPanelIfReactLoaded@moz-extension://071dca55-9c49-f249-99a4-c240c097c130/build/main.js:18:25
> @moz-extension://071dca55-9c49-f249-99a4-c240c097c130/build/main.js:37:5
> __webpack_require__@moz-extension://071dca55-9c49-f249-99a4-c240c097c130/build/main.js:9:16
> @moz-extension://071dca55-9c49-f249-99a4-c240c097c130/build/main.js:14:33
> @moz-extension://071dca55-9c49-f249-99a4-c240c097c130/build/main.js:1:2
> Current stack
> applySafeWithoutClone@resource://gre/modules/ExtensionCommon.jsm:287:133
> wrapPromise/<@resource://gre/modules/ExtensionCommon.jsm:452:13
> promise callback*wrapPromise@resource://gre/modules/ExtensionCommon.jsm:445:7
> callParentAsyncFunction@resource://gre/modules/ExtensionChild.jsm:837:12
> callAsyncFunction@resource://gre/modules/ExtensionChild.jsm:656:12
> stub@resource://gre/modules/Schemas.jsm:2224:22
> createPanelIfReactLoaded@moz-extension://071dca55-9c49-f249-99a4-c240c097c130/build/main.js:18:25
> @moz-extension://071dca55-9c49-f249-99a4-c240c097c130/build/main.js:37:5
> __webpack_require__@moz-extension://071dca55-9c49-f249-99a4-c240c097c130/build/main.js:9:16
> @moz-extension://071dca55-9c49-f249-99a4-c240c097c130/build/main.js:14:33
> @moz-extension://071dca55-9c49-f249-99a4-c240c097c130/build/main.js:1:2
> ]]

Disabling/removing the extension stops these errors.

**Comment by juliandescottes** [comment]
As discussed on Firefox devtools IRC channel, this is most likely a regression from Firefox DevTools itself, as it only breaks on very recent Nightly builds. 

I opened a bug to fix the regression : https://bugzilla.mozilla.org/show_bug.cgi?id=1392531

**Comment by bvaughn** [comment]
Nice! thanks for the assist, folks! 😄 

Seems like we should be okay to close this issue then?

**Comment by juliandescottes** [comment]
> Seems like we should be okay to close this issue then?

No objection on my side. Though maybe @squelart can verify the issue is fixed by building FF with the patches attached to https://bugzilla.mozilla.org/show_bug.cgi?id=1392531 to be sure?

**Comment by squelart** [comment]
Sorry for accusing react-devtools. :-)

Unfortunately I'm still getting an exception when trying @juliandescottes's bugzilla patch, so maybe we should keep this issue open here (in case other people experience it), and I'll close it when it's fixed.

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools
